# -*- coding: utf-8 -*-
"""FishPrediction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CgAXmaaO67CH3_buhd-EllvNDnf8vIUa
"""

!pip install tensorflow opencv-python matplotlib numpy

import os

os.makedirs("dataset/train/Fresh", exist_ok=True)
os.makedirs("dataset/train/Spoiled", exist_ok=True)

os.makedirs("dataset/test/Fresh", exist_ok=True)
os.makedirs("dataset/test/Spoiled", exist_ok=True)

print("2-class folder structure created!")

from tensorflow.keras.applications import MobileNetV2

base_model = MobileNetV2(
    weights="imagenet",
    include_top=False,
    input_shape=(224, 224, 3)
)

base_model.trainable = True

for layer in base_model.layers[:-30]:
    layer.trainable = False


print("MobileNetV2 loaded and frozen ✅")

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D, Dropout
from tensorflow.keras.optimizers import Adam

base_model.trainable = False  # Freeze first

model = Sequential([
    base_model,
    GlobalAveragePooling2D(),
    Dense(128, activation="relu"),
    Dropout(0.5),
    Dense(1, activation="sigmoid")
])

model.compile(
    optimizer=Adam(learning_rate=1e-3),
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

model.summary()

import os, random, shutil

def split_data(src, dst, ratio=0.75):
    files = os.listdir(src)
    random.shuffle(files)

    split = int(len(files) * ratio)
    test_files = files[split:]

    for f in test_files:
        shutil.move(
            os.path.join(src, f),
            os.path.join(dst, f)
        )

# 🔥 CALL THE FUNCTION OUTSIDE
split_data("dataset/train/Fresh", "dataset/test/Fresh")
split_data("dataset/train/Spoiled", "dataset/test/Spoiled")

print("Train–Test split completed ✅")

print("Train Fresh:", len(os.listdir("dataset/train/Fresh")))
print("Train Spoiled:", len(os.listdir("dataset/train/Spoiled")))
print("Test Fresh:", len(os.listdir("dataset/test/Fresh")))
print("Test Spoiled:", len(os.listdir("dataset/test/Spoiled")))

from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications.mobilenet_v2 import preprocess_input

train_gen = ImageDataGenerator(
    preprocessing_function=preprocess_input,
    rotation_range=20,
    zoom_range=0.2,
    width_shift_range=0.2,
    height_shift_range=0.2,
    horizontal_flip=True
)

test_gen = ImageDataGenerator(
    preprocessing_function=preprocess_input
)




train_data = train_gen.flow_from_directory(
    "dataset/train",
    target_size=(224,224),
    batch_size=8,
    class_mode="binary"
)

test_data = test_gen.flow_from_directory(
    "dataset/test",
    target_size=(224,224),
    batch_size=8,
    class_mode="binary",
    shuffle=False
)

fresh = len(os.listdir("dataset/train/Fresh"))
spoiled = len(os.listdir("dataset/train/Spoiled"))

class_weight = {
    0: 1.0,
    1: fresh / spoiled
}

print("Class weights:", class_weight)

history = model.fit(
    train_data,
    epochs=10,
    validation_data=test_data,
    class_weight=class_weight
)

history = model.fit(
    train_data,
    epochs=5,
    validation_data=test_data,
    class_weight=class_weight
)

from tensorflow.keras.optimizers import Adam

model.compile(
    optimizer=Adam(learning_rate=1e-4),
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

from sklearn.metrics import classification_report
pred = model.predict(test_data)
pred = (pred > 0.5).astype(int).ravel()

print(classification_report(test_data.classes, pred))

import matplotlib.pyplot as plt

# Accuracy graph
plt.plot(history.history['accuracy'], label='Training Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.legend()
plt.title('Training vs Validation Accuracy')
plt.show()

# Loss graph
plt.plot(history.history['loss'], label='Training Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()
plt.title('Training vs Validation Loss')
plt.show()

import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix
import seaborn as sns
import numpy as np

# Predict on test data
y_pred = model.predict(test_data)
y_pred = (y_pred > 0.5).astype(int).reshape(-1)

y_true = test_data.classes

# Confusion Matrix
cm = confusion_matrix(y_true, y_pred)

# Plot
plt.figure(figsize=(5,4))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Fresh', 'Spoiled'],
            yticklabels=['Fresh', 'Spoiled'])
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix')
plt.show()



model.save("fish_freshness_detection.h5")
print("Model saved successfully ✅")

!pip install gradio

import gradio as gr
import tensorflow as tf
import numpy as np
import cv2
from tensorflow.keras.applications.mobilenet_v2 import preprocess_input

# Load model
model = tf.keras.models.load_model("fish_freshness_detection.h5")


def predict_image(image):

    img = cv2.resize(image,(224,224))
    img = np.expand_dims(img, axis=0)
    img = preprocess_input(img)

    pred = model.predict(img)[0][0]

    if pred > 0.5:
        label = "🛑 Spoiled Fish"
        confidence = pred
    else:
        label = "✅ Fresh Fish"
        confidence = 1 - pred

    return label, f"{confidence*100:.2f}%"



css = """

body{
background:#0b0f17;
font-family: 'Segoe UI';
color:white;
}

/* NAVBAR */

.navbar{
display:flex;
justify-content:space-between;
align-items:center;
padding:20px 50px;
font-size:18px;
font-weight:600;
}

.nav-buttons span{
border:1px solid #ccc;
padding:6px 15px;
border-radius:20px;
margin-left:10px;
cursor:pointer;
}

/* HERO */

.hero h1{
font-size:36px;
margin-bottom:10px;
}

.hero p{
color:#cfcfcf;
max-width:500px;
}

/* FEATURE TAGS */

.tag{
background:#1e1e1e;
padding:10px 15px;
border-radius:10px;
text-align:center;
margin-top:10px;
}

/* CARD */

.card{
background:#1b1f2a;
border-radius:15px;
padding:25px;
box-shadow:0 8px 20px rgba(0,0,0,0.5);
}

/* BUTTONS */

button{
background:#12c2c2 !important;
color:white !important;
border-radius:20px !important;
font-weight:bold !important;
}

/* TEXTBOX */

textarea{
background:#111 !important;
color:white !important;
}

"""



with gr.Blocks(css=css) as demo:

    # NAVBAR
    gr.HTML("""
    <div class="navbar">
        <div><b>AquaFresh AI</b></div>
        <div class="nav-buttons">
            <span>Home</span>
            <span>About</span>
            <span>Detect</span>
        </div>
    </div>
    """)


    with gr.Row():

        # LEFT SIDE
        with gr.Column(scale=2):

            gr.HTML("""
            <div class="hero">
            <h1>Automated Fish Freshness Detection</h1>
            <p>
            An AI-powered system using deep learning (MobileNetV2)
            to classify fish freshness as Fresh or Spoiled in real-time.
            </p>
            </div>
            """)

            with gr.Row():
                gr.HTML('<div class="tag">⚡ Real-Time AI</div>')
                gr.HTML('<div class="tag">🖼 Image Based</div>')

            with gr.Row():
                gr.HTML('<div class="tag">🧠 Deep Learning</div>')
                gr.HTML('<div class="tag">🔥 Low Cost</div>')


        # RIGHT SIDE CARD
        with gr.Column(scale=1):

            with gr.Group(elem_classes="card"):

                gr.Markdown("### Upload Fish Image")

                image_input = gr.Image(
                    type="numpy",
                    label="Image",
                    height=220
                )

                predict_btn = gr.Button("Check Freshness")
                reset_btn = gr.Button("Reset")

                result = gr.Textbox(label="Prediction", interactive=False)
                confidence = gr.Textbox(label="Confidence", interactive=False)


    predict_btn.click(
        predict_image,
        inputs=image_input,
        outputs=[result, confidence]
    )


    def reset():
        return None,"",""

    reset_btn.click(
        reset,
        outputs=[image_input,result,confidence]
    )


demo.launch()